In [5]:
## MOMODOU JALLOW 
## IS19B00/157
## A87113
## Deep Learning Practical Assignment 1

### 1. Run the code in this section. Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.

In [1]:
import torch

In [2]:
X = torch.arange(9).reshape(3,3)

Y = torch.arange(9, 0, -1).reshape(3,3)

X == Y, X > Y, X < Y

(tensor([[False, False, False],
         [False, False, False],
         [False, False, False]]),
 tensor([[False, False, False],
         [False, False,  True],
         [ True,  True,  True]]),
 tensor([[ True,  True,  True],
         [ True,  True, False],
         [False, False, False]]))

### 
2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?



In [4]:
a = torch.arange(15).reshape((5, 1, 3))
b = torch.arange(15).reshape((3, -1, 5))
a, b

(tensor([[[ 0,  1,  2]],
 
         [[ 3,  4,  5]],
 
         [[ 6,  7,  8]],
 
         [[ 9, 10, 11]],
 
         [[12, 13, 14]]]),
 tensor([[[ 0,  1,  2,  3,  4]],
 
         [[ 5,  6,  7,  8,  9]],
 
         [[10, 11, 12, 13, 14]]]))

Yes, the result does match with what I expected as well as with what I learnt in the textbook.