In [1]:
import torch

In [2]:
# arange(n), we can create a vector of evenly spaced values, start-
# ing at 0 (included) and ending at n (not included).

x = torch.arange(12, dtype=torch.float32)

In [3]:
# We can inspect the total number of elements in a tensor via its numel method.

x.numel()

12

In [5]:
# Check the shape of the tensor 

x.shape

torch.Size([12])

In [6]:
# We can change the shape of a tensor without altering its size or values, by invoking reshape.

mat_X = x.reshape(3, 4)
mat_X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
# Create a tensor with all its elements zeroes  

torch.zeros(2, 3, 4) 

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
# Create a tensor with all its elements ones

torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
# Create a tensor with elements drawn from a standard
#Gaussian (normal) distribution with mean 0 and standard deviation 1.

torch.randn(3, 4)

tensor([[ 0.2878, -0.7877,  0.5395,  0.4816],
        [-3.0133,  1.0984,  0.3175,  1.7936],
        [ 1.0331,  0.4632, -1.4359, -0.9054]])

In [11]:
# Create a tensor by specifically putting in the elements 

torch.tensor([[1,2,3],[4, 5, 6],[7, 8, 9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Indexing and Slicing 

In [12]:
# We can access whole ranges of indices via slicing (e.g., X[start:stop]), where
#the returned value includes the first index (start) but not the last (stop).

mat_X[-1], mat_X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

### Altering the values of the elements in a tensor 

In [13]:
mat_X[1, 2] = 17
mat_X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
mat_X[:2, :] = 12
mat_X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### Operations With Tensors

In [16]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [17]:
# Arithmetic 
y = torch.tensor([1.0, 2, 4, 8])
z = torch.tensor([2, 2, 2, 2])
y + z, y - z, y * z, y / z, y ** z

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))