In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cpu


### Introduction to Tensors 

In [3]:
# Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# dimensions of a tensor
scalar.ndim

0

In [5]:
# Get the elements in a tensor
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([2, 3, 5])
vector

tensor([2, 3, 5])

In [11]:
# dimensions
vector.ndim

1

In [12]:
# Shape - number of elements in the tensor
vector.shape

torch.Size([3])

In [13]:
vector.size()

torch.Size([3])

In [15]:
# MATRIX
MATRIX = torch.tensor([[2, 3],
                      [4, 5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [16]:
# dimensions
MATRIX.ndim

2

In [17]:
# Size of the matrix 
MATRIX.shape

torch.Size([2, 2])

In [18]:
MATRIX.size()

torch.Size([2, 2])

In [21]:
# Indexing
MATRIX[0]

tensor([2, 3])

In [22]:
MATRIX[1][0]

tensor(4)

In [23]:
# TENSOR
TENSOR = torch.tensor([[[6, 7], 
                        [8, 9],
                       [10, 11]]])
TENSOR

tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [24]:
# Dimensions
TENSOR.ndim

3

In [25]:
# Shape
TENSOR.shape

torch.Size([1, 3, 2])