In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cpu


### Introduction to Tensors 

In [2]:
# Scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# dimensions of a tensor
scalar.ndim

0

In [4]:
# Get the elements in a tensor
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([2, 3, 5])
vector

tensor([2, 3, 5])

In [6]:
# dimensions
vector.ndim

1

In [7]:
# Shape - number of elements in the tensor
vector.shape

torch.Size([3])

In [8]:
vector.size()

torch.Size([3])

In [9]:
# MATRIX
MATRIX = torch.tensor([[2, 3],
                      [4, 5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [10]:
# dimensions
MATRIX.ndim

2

In [11]:
# Size of the matrix 
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX.size()

torch.Size([2, 2])

In [13]:
# Indexing
MATRIX[0]

tensor([2, 3])

In [14]:
MATRIX[1][0]

tensor(4)

In [15]:
# TENSOR
TENSOR = torch.tensor([[[6, 7], 
                        [8, 9],
                       [10, 11]]])
TENSOR

tensor([[[ 6,  7],
         [ 8,  9],
         [10, 11]]])

In [16]:
# Dimensions
TENSOR.ndim

3

In [17]:
# Shape
TENSOR.shape

torch.Size([1, 3, 2])

### Create Random Tensors

In [18]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5110, 0.1429, 0.8819, 0.8862],
         [0.9073, 0.7931, 0.2609, 0.4291],
         [0.3537, 0.3660, 0.7230, 0.2650]],

        [[0.4778, 0.8828, 0.0852, 0.7218],
         [0.3927, 0.4878, 0.4117, 0.4600],
         [0.9573, 0.9318, 0.3738, 0.6434]]])

In [19]:
# Size of tensor
random_tensor.shape

torch.Size([2, 3, 4])

In [20]:
# Number of dimensions
random_tensor.ndim

3

In [21]:
# Number of elements in the tensor
random_tensor.numel()

24

In [22]:
# Create random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(3, 244, 244)) # colour channels, height, width
random_image_size_tensor

tensor([[[0.7965, 0.2562, 0.9639,  ..., 0.7273, 0.8125, 0.5763],
         [0.4476, 0.6998, 0.4323,  ..., 0.6734, 0.6897, 0.1807],
         [0.7216, 0.8102, 0.3719,  ..., 0.9067, 0.7940, 0.9760],
         ...,
         [0.1827, 0.1018, 0.7420,  ..., 0.7763, 0.9219, 0.7828],
         [0.3268, 0.6694, 0.8309,  ..., 0.2774, 0.5912, 0.8609],
         [0.9296, 0.3571, 0.5974,  ..., 0.5689, 0.9612, 0.8505]],

        [[0.4921, 0.2694, 0.3581,  ..., 0.0067, 0.7953, 0.6550],
         [0.2834, 0.9701, 0.0190,  ..., 0.5168, 0.2243, 0.4922],
         [0.4427, 0.9824, 0.3924,  ..., 0.0530, 0.9550, 0.5164],
         ...,
         [0.1596, 0.9462, 0.5340,  ..., 0.7678, 0.5655, 0.1469],
         [0.8267, 0.4068, 0.2514,  ..., 0.0166, 0.8249, 0.2711],
         [0.1221, 0.8317, 0.5921,  ..., 0.6781, 0.2340, 0.2824]],

        [[0.4259, 0.4549, 0.5511,  ..., 0.0130, 0.5443, 0.9114],
         [0.6194, 0.1323, 0.4113,  ..., 0.2324, 0.0196, 0.2557],
         [0.5951, 0.4556, 0.1689,  ..., 0.5095, 0.7919, 0.

In [23]:
# Size 
random_image_size_tensor.shape

torch.Size([3, 244, 244])

In [24]:
# Number of dimensions
random_image_size_tensor.ndim

3

In [25]:
# Number of elements
random_image_size_tensor.numel()

178608

### Zeros and Ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
# Check the data type of a tensor
zeros.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

In [30]:
random_image_size_tensor.dtype

torch.float32

### Create a range of tensors and tensor-like

In [31]:
# Create a tensor with elements from 1 to 10
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
# Create a tensor_like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Important Parameters When Creating Tensors

In [33]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

### Convert Between Tensor-Data Types

In [34]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Tensor Atrributes

In [35]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9208, 0.4513, 0.2784, 0.4488],
        [0.7076, 0.6890, 0.0483, 0.0986],
        [0.4286, 0.8891, 0.3707, 0.8738]])

In [36]:
# Find out details/attributes about some_tensor
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (Tensor Operations)

In [37]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [39]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [40]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [43]:
torch.sub(tensor, 10)

tensor([-9, -8, -7])

### Matrix Multiplication

In [44]:
tensor

tensor([1, 2, 3])

In [46]:
# Element-wise multiplication
print(tensor,"*", tensor)
print(f"Equals:{tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [47]:
# Matrix multiplication(dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [58]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 3)) # Rules of matrix multiplication obeyed.

tensor([[0.8022, 0.7814, 0.3581],
        [1.1278, 1.4694, 0.9944],
        [1.3720, 1.7139, 1.1376]])